export const CITIES = [
  // Portland Metro
  {
    id: 'portland',
    name: 'Portland',
    region: 'Portland Metro',
    neighborhood: 'Nob Hill, Goose Hollow, Portland Heights, Kings Heights & Arlington Heights',
    neighborhoodDesc: 'These southwest Portland neighborhoods are packed with beautiful, older homes on hillside lots — Craftsman bungalows, Tudors, and classic Northwest architecture throughout Nob Hill, Goose Hollow, Portland Heights, Kings Heights, and Arlington Heights. The tree canopy and elevation mean roofs here deal with extra moisture, debris, and complex drainage, making regular inspections and quality materials especially important.',
    cityDesc: 'As Portland\'s largest city, we work on everything from classic Craftsman bungalows in established neighborhoods to modern mixed-use buildings downtown. Portland\'s wet winters and occasional ice storms mean roofs here take a real beating.',
    roofingNote: 'Portland homes are especially prone to moss and algae buildup due to the mild, damp climate. We recommend algae-resistant shingles and annual inspections to extend roof life.',
  },
  {
    id: 'northeast-portland',
    name: 'Northeast Portland',
    region: 'Portland Metro',
    neighborhood: 'Alberta Arts District',
    neighborhoodDesc: 'The Alberta Arts District is a beloved NE Portland corridor known for its colorful murals, local shops, and historic homes. Many of the Craftsman and Victorian-era houses here are overdue for a roof inspection.',
    cityDesc: 'Northeast Portland is home to some of the city\'s oldest and most character-rich housing stock. We regularly work on historic homes throughout NE, matching materials to the architectural style while meeting modern performance standards.',
    roofingNote: 'Older NE Portland homes often have original wood shake or early asphalt roofs approaching end of life. We can assess whether repair or full replacement is the right call.',
  },
  {
    id: 'southeast-portland',
    name: 'Southeast Portland',
    region: 'Portland Metro',
    neighborhood: 'Hawthorne, Woodstock, Lents, Mill Park, Hazelwood, Montavilla, Mt. Tabor & Parkrose',
    neighborhoodDesc: 'Southeast Portland is one of the city\'s most diverse and residential quadrants. From the bungalows and Victorians of Hawthorne and Mt. Tabor to the working-class homes of Lents, Mill Park, and Hazelwood, and the growing neighborhoods of Woodstock, Montavilla, and Parkrose — SE Portland has it all. Many of these homes were built in the 1920s–1960s and are due for a serious roof evaluation. Heavy tree coverage across SE means moss, debris, and gutter buildup are constant concerns.',
    cityDesc: 'Southeast Portland covers a wide range of home styles and ages. From mid-century ranches to early 1900s foursquares, our crews are experienced across every roof type you\'ll find in SE.',
    roofingNote: 'SE Portland\'s heavy tree coverage means gutters clog fast and roofs accumulate debris quickly. We recommend pairing any roofing project with a gutter inspection.',
  },
  {
    id: 'north-portland',
    name: 'North Portland',
    region: 'Portland Metro',
    neighborhood: 'Mississippi Avenue',
    neighborhoodDesc: 'Mississippi Avenue is North Portland\'s hip, walkable main street — full of locally-owned restaurants, boutiques, and renovated Craftsman homes. The neighborhood has seen a lot of home renovation activity in recent years.',
    cityDesc: 'North Portland has a mix of working-class bungalows, new infill construction, and renovated historic homes. We work across all of them and understand the unique permitting and inspection requirements in this area.',
    roofingNote: 'Many North Portland homes were built in the 1920s–1940s and are on their second or third roof. If yours is over 20 years old, it\'s worth having us take a look.',
  },
  {
    id: 'southwest-portland',
    name: 'Southwest Portland',
    region: 'Portland Metro',
    neighborhood: 'Multnomah Village',
    neighborhoodDesc: 'Multnomah Village is a charming pocket of SW Portland with a small-town feel — tree-lined streets, local shops, and a variety of mid-century and ranch-style homes that often need roofing updates.',
    cityDesc: 'Southwest Portland\'s hillside terrain means many homes have complex rooflines with multiple pitches, dormers, and valleys — all areas where leaks tend to develop. Our crew is experienced on steep and complex roofs.',
    roofingNote: 'The elevation and tree exposure in SW Portland can accelerate roof wear. Steeper pitches drain better but are harder to inspect — let us handle it safely.',
  },
  {
    id: 'northwest-portland',
    name: 'Northwest Portland',
    region: 'Portland Metro',
    neighborhood: 'Nob Hill',
    neighborhoodDesc: 'Nob Hill — also known as the NW 23rd neighborhood — is one of Portland\'s most upscale areas, with Victorian mansions, condo buildings, and historic apartment complexes that all require specialized roofing expertise.',
    cityDesc: 'Northwest Portland blends historic residential architecture with dense urban housing. We work on Victorian-era homes, apartment buildings, and everything in between — always with the care these properties deserve.',
    roofingNote: 'Historic properties in NW Portland may require specific materials or approaches to maintain architectural character. We\'re happy to advise on the best options.',
  },
  {
    id: 'st-johns',
    name: 'St. Johns',
    region: 'Portland Metro',
    neighborhood: 'Cathedral Park',
    neighborhoodDesc: 'Cathedral Park sits beneath the iconic St. Johns Bridge and is the heart of this tight-knit North Portland community. The neighborhood\'s older bungalows and cottages often have roofs that are well past their prime.',
    cityDesc: 'St. Johns has a strong community identity and a housing stock that skews older. We\'ve worked on dozens of homes in this neighborhood and understand the character — and the challenges — of its architecture.',
    roofingNote: 'St. Johns is close to the river, which means extra moisture exposure. Proper ventilation and moisture-resistant underlayment are especially important here.',
  },
  {
    id: 'sellwood',
    name: 'Sellwood',
    region: 'Portland Metro',
    neighborhood: 'Sellwood-Moreland',
    neighborhoodDesc: 'Sellwood-Moreland is one of Portland\'s most desirable neighborhoods — peaceful, walkable, and full of well-kept historic homes near the Willamette River. Many of these homes are getting roofing updates as part of larger renovation projects.',
    cityDesc: 'Sellwood homeowners take pride in their properties, and so do we. We work carefully on historic homes in this area, matching shingle profiles and colors to preserve the neighborhood\'s look while delivering modern performance.',
    roofingNote: 'Proximity to the Willamette means Sellwood roofs face extra humidity. We recommend high-quality underlayment and proper attic ventilation on every job here.',
  },

  // East Metro
  {
    id: 'gresham',
    name: 'Gresham',
    region: 'East Metro',
    neighborhood: 'Downtown Gresham',
    neighborhoodDesc: 'Downtown Gresham is the civic heart of Oregon\'s fourth-largest city — a mix of historic storefronts, new development, and established residential streets with a wide variety of home styles and ages.',
    cityDesc: 'Gresham\'s housing stock ranges from mid-century ranches to newer construction. We\'re a familiar face in this community and have completed roofing projects across all of Gresham\'s neighborhoods.',
    roofingNote: 'Gresham sits at slightly higher elevation than Portland and can see more wind and winter ice events. Wind-resistant shingles are worth considering here.',
  },
  {
    id: 'troutdale',
    name: 'Troutdale',
    region: 'East Metro',
    neighborhood: 'Historic Downtown Troutdale',
    neighborhoodDesc: 'Historic Downtown Troutdale is a charming gateway to the Columbia River Gorge, with antique shops, local eateries, and older homes that carry real Pacific Northwest character.',
    cityDesc: 'Troutdale\'s position at the mouth of the Gorge means it catches serious wind — the area is known for some of the strongest gusts in the metro. Roofs here need to be installed with wind resistance in mind.',
    roofingNote: 'Gorge winds can lift shingles that aren\'t properly fastened. We always follow enhanced nailing patterns for Troutdale and Gorge-adjacent properties.',
  },
  {
    id: 'fairview',
    name: 'Fairview',
    region: 'East Metro',
    neighborhood: 'Fairview Village',
    neighborhoodDesc: 'Fairview Village is a planned, walkable community built around a town square — one of the few new urbanist developments in the Portland metro, with distinct architecture that requires careful roofing work.',
    cityDesc: 'Fairview is a small but growing city with a mix of newer subdivisions and older rural properties. We work across all of them and offer free estimates throughout the area.',
    roofingNote: 'Newer construction in Fairview sometimes has builder-grade roofing that underperforms over time. An upgrade to a premium shingle can significantly extend your roof\'s life.',
  },
  {
    id: 'wood-village',
    name: 'Wood Village',
    region: 'East Metro',
    neighborhood: 'Wood Village Town Center',
    neighborhoodDesc: 'Wood Village is one of the Portland metro\'s smallest incorporated cities, with a close-knit residential feel and older housing stock that benefits from regular roofing maintenance.',
    cityDesc: 'We\'ve worked on homes throughout Wood Village and treat every job here with the same care and attention as any larger city project. No job is too small.',
    roofingNote: 'Many Wood Village homes were built in the 1950s–70s and may be approaching or past their second roof. We offer free assessments to help you plan ahead.',
  },
  {
    id: 'corbett',
    name: 'Corbett',
    region: 'East Metro',
    neighborhood: 'Crown Point Vista',
    neighborhoodDesc: 'Crown Point Vista is one of the most scenic spots in the Columbia River Gorge — and the Corbett area surrounding it has rural properties, acreage homes, and mountain cabins that all need durable roofing to handle the elements.',
    cityDesc: 'Corbett is a rural community in the Gorge with properties that face some of the harshest weather in the region. High winds, heavy rain, and occasional snow make roofing quality especially critical here.',
    roofingNote: 'Rural and elevated properties like those in Corbett benefit from impact-resistant shingles and extra attention to flashing and ventilation.',
  },
  {
    id: 'sandy',
    name: 'Sandy',
    region: 'East Metro',
    neighborhood: 'Downtown Sandy',
    neighborhoodDesc: 'Downtown Sandy is a classic small-town Oregon main street — a stop on the way to Mt. Hood with local businesses, historic buildings, and a community that takes care of its properties.',
    cityDesc: 'Sandy sits at higher elevation than the metro and sees more precipitation and occasional snow. Roofing here needs to handle real winter conditions. We bring the right materials and expertise for mountain-adjacent climates.',
    roofingNote: 'Snow load is a real consideration in Sandy. Proper structural assessment and a quality roof deck are important for homes in this area.',
  },

  // West Metro
  {
    id: 'beaverton',
    name: 'Beaverton',
    region: 'West Metro',
    neighborhood: 'Downtown Beaverton',
    neighborhoodDesc: 'Downtown Beaverton is a bustling urban center in Washington County — home to Nike\'s world headquarters nearby and a mix of established neighborhoods and new high-density development.',
    cityDesc: 'Beaverton is one of Oregon\'s fastest-growing cities with a huge range of housing styles and ages. From 1960s ranch homes to brand-new construction, our crew handles every type of roofing project in Beaverton.',
    roofingNote: 'Beaverton\'s rapid growth means many homes were built to different standards. We\'ve seen a wide range of roofing quality here — a free inspection can tell you exactly where yours stands.',
  },
  {
    id: 'hillsboro',
    name: 'Hillsboro',
    region: 'West Metro',
    neighborhood: 'Downtown Hillsboro',
    neighborhoodDesc: 'Downtown Hillsboro anchors Washington County\'s largest city — a growing tech hub home to Intel\'s largest campus. The surrounding neighborhoods range from historic Victorian homes to brand-new subdivisions.',
    cityDesc: 'Hillsboro\'s growth has been dramatic, and its housing stock reflects that diversity. We work throughout Hillsboro on everything from aging farmhouses to newly constructed neighborhoods.',
    roofingNote: 'The Tualatin Valley can be foggy and damp in winter — conditions that accelerate moss growth. We recommend moss-resistant shingles for Hillsboro homes.',
  },
  {
    id: 'tigard',
    name: 'Tigard',
    region: 'West Metro',
    neighborhood: 'Downtown Tigard',
    neighborhoodDesc: 'Downtown Tigard is undergoing a significant revitalization — new development along the Fanno Creek Trail corridor, surrounded by established residential neighborhoods with mid-century and ranch-style homes.',
    cityDesc: 'Tigard is a family-friendly suburb with a solid mix of 1970s–90s housing that\'s hitting the age where roofing replacement becomes necessary. We\'ve completed dozens of jobs throughout Tigard\'s neighborhoods.',
    roofingNote: '1970s–80s homes in Tigard are at or near the end of their original roof\'s lifespan. A proactive replacement now avoids costly interior water damage later.',
  },
  {
    id: 'tualatin',
    name: 'Tualatin',
    region: 'West Metro',
    neighborhood: 'Tualatin Commons',
    neighborhoodDesc: 'Tualatin Commons is the city\'s centerpiece — a lake-front town square surrounded by shops, restaurants, and residential developments. The waterfront setting means extra moisture exposure for nearby homes.',
    cityDesc: 'Tualatin is a well-planned suburb with newer housing stock and a strong sense of community. We serve homeowners throughout Tualatin and offer fast, reliable estimates.',
    roofingNote: 'Proximity to Tualatin Lake and the river means higher humidity levels for nearby homes. Proper attic ventilation is especially important to prevent moisture damage.',
  },
  {
    id: 'sherwood',
    name: 'Sherwood',
    region: 'West Metro',
    neighborhood: 'Old Town Sherwood',
    neighborhoodDesc: 'Old Town Sherwood is a picturesque historic district with Victorian-era buildings, antique shops, and charming residences that require careful, detail-oriented roofing work.',
    cityDesc: 'Sherwood is one of Washington County\'s most desirable communities — well-kept homes, great schools, and a small-town feel. We\'re proud to serve homeowners here and take extra care on every project.',
    roofingNote: 'Historic homes in Old Town Sherwood may have original wood shake or early composite roofing. We can advise on the best modern replacement that preserves the home\'s character.',
  },
  {
    id: 'lake-oswego',
    name: 'Lake Oswego',
    region: 'West Metro',
    neighborhood: 'Lake Grove',
    neighborhoodDesc: 'Lake Grove is one of Lake Oswego\'s most established neighborhoods — lakeside living, large lots, and upscale homes that demand the highest quality roofing craftsmanship.',
    cityDesc: 'Lake Oswego is known for its beautiful homes and high standards, and we match them on every job. Whether it\'s a lakeside estate or a hillside contemporary, our crew delivers premium results.',
    roofingNote: 'High-end homes in Lake Oswego deserve premium materials. We offer architectural shingles, metal roofing, and designer product lines that match the caliber of these properties.',
  },
  {
    id: 'west-linn',
    name: 'West Linn',
    region: 'West Metro',
    neighborhood: 'Willamette',
    neighborhoodDesc: 'The Willamette neighborhood in West Linn sits along the river with a charming historic downtown, older homes with real character, and views that make every roofing project worth getting right.',
    cityDesc: 'West Linn\'s hillside terrain and older housing stock create interesting roofing challenges — multiple pitches, valleys, and mature tree canopy. We\'re experienced on complex rooflines throughout West Linn.',
    roofingNote: 'Hillside homes in West Linn often have complex drainage paths. We assess every valley and flashing point carefully to ensure water exits the roof properly.',
  },
  {
    id: 'wilsonville',
    name: 'Wilsonville',
    region: 'West Metro',
    neighborhood: 'Town Center',
    neighborhoodDesc: 'Wilsonville Town Center is the hub of this fast-growing southern suburb — planned retail, restaurants, and residential neighborhoods that have expanded rapidly over the past two decades.',
    cityDesc: 'Wilsonville is one of the metro\'s newest and fastest-growing communities. Much of its housing is 15–25 years old, which puts a lot of roofs right at the point where inspection or replacement makes sense.',
    roofingNote: 'Homes built in the early 2000s in Wilsonville are approaching the end of their 20–25 year shingle life. Now is a great time to assess and plan ahead.',
  },

  // Clark County WA
  {
    id: 'vancouver',
    name: 'Vancouver',
    region: 'North & Clark County (WA)',
    neighborhood: 'Uptown Village',
    neighborhoodDesc: 'Uptown Village is Vancouver\'s most walkable and eclectic neighborhood — historic bungalows, independent shops, and a creative community that values quality craftsmanship on their homes.',
    cityDesc: 'Vancouver, WA is the largest city in Clark County and shares much of Portland\'s character across the river. We\'re fully licensed in Washington and regularly work on homes throughout Vancouver.',
    roofingNote: 'We hold Washington state license TOUGHRL772B4 and are fully permitted to work in Vancouver and all of Clark County. No extra paperwork on your end.',
  },
  {
    id: 'camas',
    name: 'Camas',
    region: 'North & Clark County (WA)',
    neighborhood: 'Downtown Camas',
    neighborhoodDesc: 'Downtown Camas is one of Clark County\'s hidden gems — a beautifully preserved historic downtown surrounded by newer high-end residential neighborhoods along the Columbia River.',
    cityDesc: 'Camas attracts discerning homeowners who care about quality, and we bring that same standard to every roofing project. From historic downtown homes to newer estates, we serve all of Camas.',
    roofingNote: 'Camas\'s riverfront location creates extra wind and moisture exposure. We recommend premium underlayment and wind-rated shingles for properties near the water.',
  },
  {
    id: 'washougal',
    name: 'Washougal',
    region: 'North & Clark County (WA)',
    neighborhood: 'Downtown Washougal',
    neighborhoodDesc: 'Downtown Washougal sits at the gateway to the Columbia River Gorge on the Washington side — a small, tight-knit community with a mix of older homes and newer development.',
    cityDesc: 'Washougal\'s Gorge-adjacent location means it deals with the same powerful winds as Troutdale across the river. We use enhanced installation techniques for all Washougal roofing projects.',
    roofingNote: 'Wind is the number one roofing threat in Washougal. Class 4 impact-resistant shingles and proper nailing patterns are strongly recommended.',
  },
  {
    id: 'battle-ground',
    name: 'Battle Ground',
    region: 'North & Clark County (WA)',
    neighborhood: 'Downtown Battle Ground',
    neighborhoodDesc: 'Downtown Battle Ground is a charming small-city center in north Clark County — surrounded by rural properties, hobby farms, and newer residential subdivisions.',
    cityDesc: 'Battle Ground has seen significant growth as families move north from the Portland metro. We serve both the older established homes and the newer subdivisions throughout the area.',
    roofingNote: 'North Clark County can see heavier rainfall than the immediate Portland area. Quality underlayment and properly sealed flashing are critical here.',
  },
  {
    id: 'ridgefield',
    name: 'Ridgefield',
    region: 'North & Clark County (WA)',
    neighborhood: 'Downtown Ridgefield',
    neighborhoodDesc: 'Downtown Ridgefield is a small historic core surrounded by rapidly growing residential neighborhoods — one of Clark County\'s fastest-expanding communities with a mix of established and brand-new homes.',
    cityDesc: 'Ridgefield\'s rapid growth means a lot of newer construction with varying quality levels. We inspect and work on homes at all stages of age throughout Ridgefield.',
    roofingNote: 'Fast-growth areas like Ridgefield sometimes have builder-grade roofing installed to minimum standards. An upgrade pays for itself quickly in longevity and energy savings.',
  },
  {
    id: 'la-center',
    name: 'La Center',
    region: 'North & Clark County (WA)',
    neighborhood: 'La Center Town Center',
    neighborhoodDesc: 'La Center is a small rural city in northern Clark County with a tight-knit community, older homes, and acreage properties that require durable roofing built for the elements.',
    cityDesc: 'La Center\'s rural character means homes here are often more exposed to weather than those in denser suburbs. We bring the same quality and care to every La Center project, no matter the size.',
    roofingNote: 'Rural properties in La Center face more wind and rain exposure without the protection of surrounding buildings. Extra attention to flashing and ventilation pays off here.',
  },

  // South Metro
  {
    id: 'milwaukie',
    name: 'Milwaukie',
    region: 'South Metro',
    neighborhood: 'Downtown Milwaukie',
    neighborhoodDesc: 'Downtown Milwaukie is a revitalized small-city center just south of Portland — historic buildings, local restaurants, and a mix of mid-century homes and new infill development along the light rail corridor.',
    cityDesc: 'Milwaukie is a close-in suburb with a strong identity and older housing stock. Many homes here are mid-century or earlier, and roofing is a common update as owners invest in their properties.',
    roofingNote: 'Milwaukie\'s older homes often have original or first-replacement roofs. If your home was built before 1990, a free inspection is a smart first step.',
  },
  {
    id: 'oregon-city',
    name: 'Oregon City',
    region: 'South Metro',
    neighborhood: 'Downtown Oregon City',
    neighborhoodDesc: 'Downtown Oregon City perches dramatically on a basalt bluff above the Willamette Falls — Oregon\'s oldest city, with Victorian-era architecture and historic homes that require specialized roofing expertise.',
    cityDesc: 'As the end of the Oregon Trail, Oregon City has a proud history reflected in its older architecture. We work carefully on these historic properties, preserving character while meeting modern performance standards.',
    roofingNote: 'Oregon City\'s historic homes may have original wood shake, slate, or early asphalt roofing. We have experience with historic materials and can advise on period-appropriate replacements.',
  },
  {
    id: 'gladstone',
    name: 'Gladstone',
    region: 'South Metro',
    neighborhood: 'Gladstone Town Center',
    neighborhoodDesc: 'Gladstone\'s compact town center sits between the Clackamas and Willamette Rivers — a small community with older housing stock and great character that benefits from regular roofing upkeep.',
    cityDesc: 'Gladstone is one of the metro\'s smaller cities, but we give every job here the same full attention. Many Gladstone homes are mid-century or older — prime candidates for roof inspection.',
    roofingNote: 'Homes near the river in Gladstone deal with extra moisture. Proper ventilation and quality underlayment are especially important in this zone.',
  },
  {
    id: 'canby',
    name: 'Canby',
    region: 'South Metro',
    neighborhood: 'Downtown Canby',
    neighborhoodDesc: 'Downtown Canby is a quiet, friendly small-town core in the heart of the Willamette Valley — surrounded by farms, nurseries, and residential neighborhoods with a mix of older and newer homes.',
    cityDesc: 'Canby sits in the agricultural heart of Clackamas County. We serve homeowners throughout Canby and the surrounding area, including rural properties on larger lots.',
    roofingNote: 'Canby\'s valley location means heavier fog and moisture in fall and winter. Moss-resistant shingles and annual gutter cleaning are smart investments here.',
  },
  {
    id: 'clackamas',
    name: 'Clackamas',
    region: 'South Metro',
    neighborhood: 'Clackamas Town Center',
    neighborhoodDesc: 'The Clackamas Town Center area is one of the metro\'s major commercial and residential hubs — surrounded by established subdivisions and newer developments that span several decades of construction.',
    cityDesc: 'The Clackamas unincorporated area covers a wide range of neighborhoods and home ages. We work throughout the area and can have someone out for a free estimate quickly.',
    roofingNote: 'The Clackamas area saw major development in the 1980s–2000s. Homes from that era are commonly hitting their first major roofing decision point.',
  },
  {
    id: 'happy-valley',
    name: 'Happy Valley',
    region: 'South Metro',
    neighborhood: 'Sunnyside',
    neighborhoodDesc: 'Sunnyside is one of Happy Valley\'s most established areas — a hillside neighborhood with newer homes, great views, and an active community that values home maintenance and quality.',
    cityDesc: 'Happy Valley is one of Oregon\'s fastest-growing cities, with newer housing stock and high homeowner standards. We serve the entire Happy Valley area and consistently deliver the quality these homes deserve.',
    roofingNote: 'Happy Valley\'s hillside terrain means complex rooflines and multiple drainage paths. We inspect every valley and transition point to ensure long-term performance.',
  },
]

export function getCityById(id) {
  return CITIES.find(c => c.id === id)
}

export function getCityByName(name) {
  return CITIES.find(c => c.name === name)
}
