export const CITIES = [
  // Portland Metro
  {
    id: 'portland',
    name: 'Portland',
    region: 'Portland Metro',
    neighborhood: 'Nob Hill, Goose Hollow, Portland Heights, Kings Heights, Arlington Heights, Irvington, Laurelhurst & Eastmoreland',
    neighborhoodDesc: 'Portland\'s residential neighborhoods span the entire city — from the hillside Craftsman bungalows of Nob Hill, Portland Heights, Kings Heights, and Arlington Heights, to the tree-lined streets of Irvington and Laurelhurst in the northeast, and the stately historic homes of Eastmoreland in the southeast. Goose Hollow rounds out the mix with older urban housing close to downtown. Across all of these areas, roofs deal with Portland\'s persistent moisture, heavy tree canopy, and aging housing stock that often needs a serious update.',
    cityDesc: 'As Portland\'s largest city, we work on everything from classic Craftsman bungalows in established neighborhoods to older urban homes and hillside properties. Portland\'s wet winters and occasional ice storms mean roofs here take a real beating.',
    roofingNote: 'Portland homes are especially prone to moss and algae buildup due to the mild, damp climate. We recommend algae-resistant shingles and annual inspections to extend roof life.',
  },
  {
    id: 'northeast-portland',
    name: 'Northeast Portland',
    region: 'Portland Metro',
    neighborhood: 'Alberta Arts District, Irvington, Beaumont-Wilshire & Alameda',
    neighborhoodDesc: 'Northeast Portland is home to some of Portland\'s most cherished residential neighborhoods. The Alberta Arts District is packed with renovated Craftsman homes and bungalows. Irvington is one of the city\'s most prestigious historic districts, full of large Victorian and Colonial Revival homes. Beaumont-Wilshire offers quiet streets lined with 1920s–30s bungalows, and Alameda sits on a ridge with stunning views and older homes that are prime candidates for roofing updates.',
    cityDesc: 'Northeast Portland is home to some of the city\'s oldest and most character-rich housing stock. We regularly work on historic homes throughout NE, matching materials to the architectural style while meeting modern performance standards.',
    roofingNote: 'Older NE Portland homes often have original wood shake or early asphalt roofs approaching end of life. We can assess whether repair or full replacement is the right call.',
  },
  {
    id: 'southeast-portland',
    name: 'Southeast Portland',
    region: 'Portland Metro',
    neighborhood: 'Hawthorne, Woodstock, Lents, Mill Park, Hazelwood, Montavilla, Mt. Tabor, Parkrose, Foster-Powell, Richmond & Creston-Kenilworth',
    neighborhoodDesc: 'Southeast Portland is one of the city\'s most diverse and residential quadrants. From the bungalows and Victorians of Hawthorne, Mt. Tabor, Richmond, and Foster-Powell to the working-class homes of Lents, Mill Park, Hazelwood, and Creston-Kenilworth, and the growing neighborhoods of Woodstock, Montavilla, and Parkrose — SE Portland has it all. Many of these homes were built in the 1920s–1960s and are due for a serious roof evaluation. Heavy tree coverage across SE means moss, debris, and gutter buildup are constant concerns.',
    cityDesc: 'Southeast Portland covers a wide range of home styles and ages. From mid-century ranches to early 1900s foursquares, our crews are experienced across every roof type you\'ll find in SE.',
    roofingNote: 'SE Portland\'s heavy tree coverage means gutters clog fast and roofs accumulate debris quickly. We recommend pairing any roofing project with a gutter inspection.',
  },
  {
    id: 'north-portland',
    name: 'North Portland',
    region: 'Portland Metro',
    neighborhood: 'Mississippi Avenue, Arbor Lodge, Kenton & Portsmouth',
    neighborhoodDesc: 'North Portland\'s residential neighborhoods each have their own personality. Mississippi Avenue is the hip commercial heart surrounded by renovated bungalows. Arbor Lodge is a quiet, family-friendly neighborhood with mid-century homes and mature trees. Kenton has a proud working-class history with older housing stock ripe for updates. Portsmouth is one of North Portland\'s most established neighborhoods, with solid Craftsman homes and good bones that deserve quality roofing.',
    cityDesc: 'North Portland has a mix of working-class bungalows, new infill construction, and renovated historic homes. We work across all of them and understand the unique permitting and inspection requirements in this area.',
    roofingNote: 'Many North Portland homes were built in the 1920s–1940s and are on their second or third roof. If yours is over 20 years old, it\'s worth having us take a look.',
  },
  {
    id: 'southwest-portland',
    name: 'Southwest Portland',
    region: 'Portland Metro',
    neighborhood: 'Multnomah Village, Hillsdale, Maplewood & Vermont Hills',
    neighborhoodDesc: 'Southwest Portland\'s residential neighborhoods are defined by their hillside character and established charm. Multnomah Village is a beloved pocket community with mid-century homes and a village feel. Hillsdale is a quiet hilltop neighborhood with ranch-style homes and excellent tree cover. Maplewood and Vermont Hills are tucked-away residential areas with older homes on wooded lots — beautiful settings that come with real roofing challenges due to shade, moisture, and debris.',
    cityDesc: 'Southwest Portland\'s hillside terrain means many homes have complex rooflines with multiple pitches, dormers, and valleys — all areas where leaks tend to develop. Our crew is experienced on steep and complex roofs.',
    roofingNote: 'The elevation and tree exposure in SW Portland can accelerate roof wear. Steeper pitches drain better but are harder to inspect — let us handle it safely.',
  },
  {
    id: 'northwest-portland',
    name: 'Northwest Portland',
    region: 'Portland Metro',
    neighborhood: 'Nob Hill, Willamette Heights, Linnton & Skyline',
    neighborhoodDesc: 'Northwest Portland\'s residential areas offer a range of housing styles and settings. Nob Hill (NW 23rd) has Victorian-era homes and historic apartment buildings. Willamette Heights sits on a bluff above the Willamette with stunning older homes and challenging steep-lot rooflines. Linnton is a small riverside community with older working-class housing. Skyline runs along the West Hills ridge with spacious properties and views — all with roofs that need to handle serious Pacific Northwest weather.',
    cityDesc: 'Northwest Portland blends historic residential architecture with hillside properties and urban housing. We work on Victorian-era homes, hillside cottages, and everything in between — always with the care these properties deserve.',
    roofingNote: 'Historic properties in NW Portland may require specific materials or approaches to maintain architectural character. We\'re happy to advise on the best options.',
  },
  {
    id: 'st-johns',
    name: 'St. Johns',
    region: 'Portland Metro',
    neighborhood: 'Cathedral Park, University Park, Pier District & Arbor Lodge',
    neighborhoodDesc: 'St. Johns and its surrounding neighborhoods make up one of North Portland\'s most character-rich corners. Cathedral Park sits beneath the iconic bridge with older bungalows and cottages close to the river. University Park is a quiet residential neighborhood with 1920s–40s homes and good street trees. The Pier District is close to the waterfront with older housing stock. Arbor Lodge borders St. Johns with solid mid-century homes that are frequently in need of roofing updates.',
    cityDesc: 'St. Johns has a strong community identity and a housing stock that skews older. We\'ve worked on dozens of homes in this neighborhood and understand the character — and the challenges — of its architecture.',
    roofingNote: 'St. Johns is close to the river, which means extra moisture exposure. Proper ventilation and moisture-resistant underlayment are especially important here.',
  },
  {
    id: 'sellwood',
    name: 'Sellwood',
    region: 'Portland Metro',
    neighborhood: 'Sellwood-Moreland, Westmoreland, Brooklyn & Ardenwald',
    neighborhoodDesc: 'The Sellwood area encompasses several beloved south Portland neighborhoods, all with strong residential character. Sellwood-Moreland is known for its antique shops and beautifully maintained historic homes. Westmoreland sits around the duck pond with charming bungalows and Craftsman homes. Brooklyn is a transitioning neighborhood with older housing stock and strong bones. Ardenwald straddles the Milwaukie border with established homes and mature trees that keep gutters busy year-round.',
    cityDesc: 'Sellwood homeowners take pride in their properties, and so do we. We work carefully on historic homes in this area, matching shingle profiles and colors to preserve the neighborhood\'s look while delivering modern performance.',
    roofingNote: 'Proximity to the Willamette means Sellwood roofs face extra humidity. We recommend high-quality underlayment and proper attic ventilation on every job here.',
  },

  // East Metro
  {
    id: 'gresham',
    name: 'Gresham',
    region: 'East Metro',
    neighborhood: 'Gresham, Rockwood, Centennial & Pleasant Valley',
    neighborhoodDesc: 'Gresham\'s residential neighborhoods cover a wide range of eras and styles. Gresham has older established homes along residential streets. Rockwood is a dense, diverse neighborhood with mid-century housing in need of roofing attention. Centennial is an established residential area with ranch and split-level homes from the 1960s–80s. Pleasant Valley on Gresham\'s southern edge has newer and rural-residential properties with different roofing needs — we handle all of them.',
    cityDesc: 'Gresham\'s housing stock ranges from mid-century ranches to newer construction. We\'re a familiar face in this community and have completed roofing projects across all of Gresham\'s neighborhoods.',
    roofingNote: 'Gresham sits at slightly higher elevation than Portland and can see more wind and winter ice events. Wind-resistant shingles are worth considering here.',
  },
  {
    id: 'troutdale',
    name: 'Troutdale',
    region: 'East Metro',
    neighborhood: 'Historic Troutdale, Glenn Otto Park, Crown Point & Lewis and Clark',
    neighborhoodDesc: 'Troutdale\'s residential areas are shaped by the Columbia River Gorge on one side and established suburban neighborhoods on the other. The historic downtown area has older homes with real character. The Glenn Otto Park neighborhood sits along the Sandy River with homes that face significant moisture and wind exposure. Crown Point and Lewis and Clark neighborhoods are established residential pockets with a mix of mid-century and older homes that bear the brunt of Gorge wind events.',
    cityDesc: 'Troutdale\'s position at the mouth of the Gorge means it catches serious wind — the area is known for some of the strongest gusts in the metro. Roofs here need to be installed with wind resistance in mind.',
    roofingNote: 'Gorge winds can lift shingles that aren\'t properly fastened. We always follow enhanced nailing patterns for Troutdale and Gorge-adjacent properties.',
  },
  {
    id: 'fairview',
    name: 'Fairview',
    region: 'East Metro',
    neighborhood: 'Fairview Village, Blue Lake, Salish Pines & Pleasant View',
    neighborhoodDesc: 'Fairview\'s neighborhoods range from the planned walkable community of Fairview Village to the waterfront homes near Blue Lake, the established Salish Pines subdivision, and the quieter Pleasant View residential areas. Homes near Blue Lake deal with extra moisture from the water, while inland neighborhoods have more typical Portland-area roofing conditions — moss, debris, and aging asphalt shingles.',
    cityDesc: 'Fairview is a small but growing city with a mix of newer subdivisions and older rural properties. We work across all of them and offer free estimates throughout the area.',
    roofingNote: 'Newer construction in Fairview sometimes has builder-grade roofing that underperforms over time. An upgrade to a premium shingle can significantly extend your roof\'s life.',
  },
  {
    id: 'wood-village',
    name: 'Wood Village',
    region: 'East Metro',
    neighborhood: 'Wood Village Town Center, Glenfair & Parklane',
    neighborhoodDesc: 'Wood Village is one of the metro\'s smallest cities, but its residential neighborhoods have real character. The Town Center area has older homes along established streets. Glenfair and Parklane are tight residential pockets with mid-century housing that\'s frequently in need of roofing updates. Despite the small city footprint, we treat every Wood Village job with the same full attention we bring to any project.',
    cityDesc: 'We\'ve worked on homes throughout Wood Village and treat every job here with the same care and attention as any larger city project. No job is too small.',
    roofingNote: 'Many Wood Village homes were built in the 1950s–70s and may be approaching or past their second roof. We offer free assessments to help you plan ahead.',
  },
  {
    id: 'corbett',
    name: 'Corbett',
    region: 'East Metro',
    neighborhood: 'Crown Point Vista, Springdale, Larch Mountain & Bridal Veil',
    neighborhoodDesc: 'The Corbett area encompasses several rural communities in the Columbia River Gorge. Crown Point Vista is the scenic heart of the area with acreage homes facing serious wind exposure. Springdale is a small farming community with older rural homes. Larch Mountain has forested properties at elevation that deal with snow load and heavy precipitation. Bridal Veil is one of the Gorge\'s most scenic spots with rural homes that need durable, weather-resistant roofing above all else.',
    cityDesc: 'Corbett is a rural community in the Gorge with properties that face some of the harshest weather in the region. High winds, heavy rain, and occasional snow make roofing quality especially critical here.',
    roofingNote: 'Rural and elevated properties like those in Corbett benefit from impact-resistant shingles and extra attention to flashing and ventilation.',
  },
  {
    id: 'sandy',
    name: 'Sandy',
    region: 'East Metro',
    neighborhood: 'Sandy, Meinig Park, Revenue Bridge & Boring',
    neighborhoodDesc: 'Sandy and its surrounding communities sit at the foothills of Mt. Hood with a mix of small-town neighborhoods and rural residential properties. Sandy has older homes along tree-lined streets. Meinig Park is a pleasant residential area with established homes. Revenue Bridge is a rural-residential community outside of town. Boring — Sandy\'s neighbor to the west — is a small unincorporated community with acreage homes that face the same mountain-adjacent weather challenges.',
    cityDesc: 'Sandy sits at higher elevation than the metro and sees more precipitation and occasional snow. Roofing here needs to handle real winter conditions. We bring the right materials and expertise for mountain-adjacent climates.',
    roofingNote: 'Snow load is a real consideration in Sandy. Proper structural assessment and a quality roof deck are important for homes in this area.',
  },

  // West Metro
  {
    id: 'beaverton',
    name: 'Beaverton',
    region: 'West Metro',
    neighborhood: 'Beaverton, Cedar Hills, Raleigh Hills & Vose',
    neighborhoodDesc: 'Beaverton\'s residential neighborhoods span decades of development. Beaverton has older established neighborhoods with homes from the 1950s–70s. Cedar Hills is one of Washington County\'s earliest planned residential communities — mid-century ranch homes on generous lots, many now needing full roof replacements. Raleigh Hills straddles the Beaverton-Portland line with hillside homes and mature landscaping. Vose is a quiet residential pocket with solid mid-century housing stock.',
    cityDesc: 'Beaverton is one of Oregon\'s fastest-growing cities with a huge range of housing styles and ages. From 1960s ranch homes to brand-new construction, our crew handles every type of roofing project in Beaverton.',
    roofingNote: 'Beaverton\'s rapid growth means many homes were built to different standards. We\'ve seen a wide range of roofing quality here — a free inspection can tell you exactly where yours stands.',
  },
  {
    id: 'hillsboro',
    name: 'Hillsboro',
    region: 'West Metro',
    neighborhood: 'Hillsboro, Orenco, Tanasbourne & South Hillsboro',
    neighborhoodDesc: 'Hillsboro\'s neighborhoods reflect its evolution from a small farming town to one of Oregon\'s largest cities. Hillsboro has historic residential streets with older homes that need updating. Orenco is a new urbanist community with well-built homes around a walkable town center. Tanasbourne is an established suburban area with 1990s–2000s housing hitting the age for first replacement. South Hillsboro is the city\'s newest master-planned expansion — brand-new construction going in right now.',
    cityDesc: 'Hillsboro\'s growth has been dramatic, and its housing stock reflects that diversity. We work throughout Hillsboro on everything from aging farmhouses to newly constructed neighborhoods.',
    roofingNote: 'The Tualatin Valley can be foggy and damp in winter — conditions that accelerate moss growth. We recommend moss-resistant shingles for Hillsboro homes.',
  },
  {
    id: 'tigard',
    name: 'Tigard',
    region: 'West Metro',
    neighborhood: 'Tigard, Bull Mountain, Metzger & Summerlake',
    neighborhoodDesc: 'Tigard\'s residential neighborhoods have a strong suburban character with homes spanning the 1960s through 2000s. Tigard has older established streets undergoing revitalization. Bull Mountain is one of Washington County\'s most desirable hillside communities — newer homes with complex rooflines and great views. Metzger is a dense residential area bordering Portland with mid-century housing in need of attention. Summerlake is a planned community with 1980s–90s homes now hitting their first major roofing decision point.',
    cityDesc: 'Tigard is a family-friendly suburb with a solid mix of 1970s–90s housing that\'s hitting the age where roofing replacement becomes necessary. We\'ve completed dozens of jobs throughout Tigard\'s neighborhoods.',
    roofingNote: '1970s–80s homes in Tigard are at or near the end of their original roof\'s lifespan. A proactive replacement now avoids costly interior water damage later.',
  },
  {
    id: 'tualatin',
    name: 'Tualatin',
    region: 'West Metro',
    neighborhood: 'Tualatin Commons, Ibach, Bridgeport & Nyberg',
    neighborhoodDesc: 'Tualatin\'s residential neighborhoods are well-planned and family-oriented. The Tualatin Commons area has waterfront homes with extra moisture exposure. Ibach is one of Tualatin\'s older residential areas with mid-century and 1970s homes. Bridgeport sits near the popular shopping district with established neighborhoods behind it. Nyberg is a newer residential area with homes from the 1990s–2000s approaching their first major roofing service interval.',
    cityDesc: 'Tualatin is a well-planned suburb with newer housing stock and a strong sense of community. We serve homeowners throughout Tualatin and offer fast, reliable estimates.',
    roofingNote: 'Proximity to Tualatin Lake and the river means higher humidity levels for nearby homes. Proper attic ventilation is especially important to prevent moisture damage.',
  },
  {
    id: 'sherwood',
    name: 'Sherwood',
    region: 'West Metro',
    neighborhood: 'Old Town Sherwood, Elwert, Sherwood Heights & Archer Farms',
    neighborhoodDesc: 'Sherwood\'s residential neighborhoods blend historic character with newer family-oriented development. Old Town Sherwood has Victorian-era homes and older bungalows requiring careful, detail-oriented work. Elwert and Sherwood Heights are established mid-to-late-century neighborhoods with ranch and split-level homes at the roofing decision point. Archer Farms is a newer subdivision with well-built homes that benefit from proactive maintenance to protect the investment.',
    cityDesc: 'Sherwood is one of Washington County\'s most desirable communities — well-kept homes, great schools, and a small-town feel. We\'re proud to serve homeowners here and take extra care on every project.',
    roofingNote: 'Historic homes in Old Town Sherwood may have original wood shake or early composite roofing. We can advise on the best modern replacement that preserves the home\'s character.',
  },
  {
    id: 'lake-oswego',
    name: 'Lake Oswego',
    region: 'West Metro',
    neighborhood: 'Lake Grove, First Addition, Westlake & Lake Forest',
    neighborhoodDesc: 'Lake Oswego\'s neighborhoods are among the most sought-after in the Portland metro. Lake Grove is an established waterfront community with upscale homes on generous lots. The First Addition is Lake Oswego\'s original residential neighborhood — some of the most historic and architecturally significant homes in the city. Westlake is a mid-century neighborhood with gracious homes and mature landscaping. Lake Forest has newer luxury homes with high-end finishes that deserve matching quality in every roofing decision.',
    cityDesc: 'Lake Oswego is known for its beautiful homes and high standards, and we match them on every job. Whether it\'s a lakeside estate or a hillside contemporary, our crew delivers premium results.',
    roofingNote: 'High-end homes in Lake Oswego deserve premium materials. We offer architectural shingles, metal roofing, and designer product lines that match the caliber of these properties.',
  },
  {
    id: 'west-linn',
    name: 'West Linn',
    region: 'West Metro',
    neighborhood: 'Willamette, Rosemont, Tanner Basin & Sunset',
    neighborhoodDesc: 'West Linn\'s neighborhoods are defined by hillside terrain, mature trees, and a strong sense of community. The Willamette neighborhood is the historic riverfront core with older homes and charming character. Rosemont is a desirable hillside neighborhood with mid-to-late-century homes and complex rooflines. Tanner Basin sits in a valley with newer homes and good drainage challenges. Sunset is a quieter residential pocket with established homes and the mature tree canopy that keeps roofs and gutters working hard.',
    cityDesc: 'West Linn\'s hillside terrain and older housing stock create interesting roofing challenges — multiple pitches, valleys, and mature tree canopy. We\'re experienced on complex rooflines throughout West Linn.',
    roofingNote: 'Hillside homes in West Linn often have complex drainage paths. We assess every valley and flashing point carefully to ensure water exits the roof properly.',
  },
  {
    id: 'wilsonville',
    name: 'Wilsonville',
    region: 'West Metro',
    neighborhood: 'Town Center, Villebois, Charbonneau & Coffee Lake Estates',
    neighborhoodDesc: 'Wilsonville\'s neighborhoods are largely newer but already seeing roofing needs emerge. The Town Center area has the city\'s early residential development from the 1980s–90s. Villebois is a large, beautifully planned new urbanist community with well-built homes that still benefit from regular maintenance. Charbonneau is a golf-course community with 1970s–90s homes — many now at the age for full roof replacement. Coffee Lake Estates has larger lots and custom homes that deserve premium roofing materials.',
    cityDesc: 'Wilsonville is one of the metro\'s newest and fastest-growing communities. Much of its housing is 15–25 years old, which puts a lot of roofs right at the point where inspection or replacement makes sense.',
    roofingNote: 'Homes built in the early 2000s in Wilsonville are approaching the end of their 20–25 year shingle life. Now is a great time to assess and plan ahead.',
  },

  // Clark County WA
  {
    id: 'vancouver',
    name: 'Vancouver',
    region: 'North & Clark County (WA)',
    neighborhood: 'Uptown Village, Hough, Shumway & Carter Park',
    neighborhoodDesc: 'Vancouver\'s residential neighborhoods north of the Columbia River have real character and history. Uptown Village is the walkable historic heart with bungalows and older homes under the tree canopy. Hough is one of Vancouver\'s most established historic districts — large older homes, many approaching or past their second roof. Shumway is a quiet residential neighborhood with early 20th century housing stock. Carter Park is a mid-century neighborhood with ranch and split-level homes that are prime candidates for roofing updates.',
    cityDesc: 'Vancouver, WA is the largest city in Clark County and shares much of Portland\'s character across the river. We\'re fully licensed in Washington and regularly work on homes throughout Vancouver.',
    roofingNote: 'We hold Washington state license TOUGHRL772B4 and are fully permitted to work in Vancouver and all of Clark County. No extra paperwork on your end.',
  },
  {
    id: 'camas',
    name: 'Camas',
    region: 'North & Clark County (WA)',
    neighborhood: 'Camas, Prune Hill, Lacamas Shores & Grass Valley',
    neighborhoodDesc: 'Camas\'s neighborhoods combine historic charm with newer upscale development. Camas has beautifully preserved older homes on tree-lined streets. Prune Hill is one of Clark County\'s most desirable hillside neighborhoods — newer custom homes with great views and complex rooflines. Lacamas Shores wraps around the lake with waterfront and near-water homes facing extra moisture. Grass Valley is an established residential area with mid-century homes that are hitting the roofing decision point.',
    cityDesc: 'Camas attracts discerning homeowners who care about quality, and we bring that same standard to every roofing project. From historic downtown homes to newer estates, we serve all of Camas.',
    roofingNote: 'Camas\'s riverfront location creates extra wind and moisture exposure. We recommend premium underlayment and wind-rated shingles for properties near the water.',
  },
  {
    id: 'washougal',
    name: 'Washougal',
    region: 'North & Clark County (WA)',
    neighborhood: 'Washougal, Canyon Creek, Cape Horn & Evergreen Heights',
    neighborhoodDesc: 'Washougal\'s residential areas sit at the Gorge\'s edge with real weather exposure. Washougal has older established neighborhoods with homes that have seen decades of Gorge wind and rain. Canyon Creek is a newer residential development with suburban homes that still need Gorge-appropriate roofing. Cape Horn is a rural area east of town with acreage homes facing the most intense weather in the region. Evergreen Heights is a mid-century neighborhood with solid housing stock in need of modernization.',
    cityDesc: 'Washougal\'s Gorge-adjacent location means it deals with the same powerful winds as Troutdale across the river. We use enhanced installation techniques for all Washougal roofing projects.',
    roofingNote: 'Wind is the number one roofing threat in Washougal. Class 4 impact-resistant shingles and proper nailing patterns are strongly recommended.',
  },
  {
    id: 'battle-ground',
    name: 'Battle Ground',
    region: 'North & Clark County (WA)',
    neighborhood: 'Battle Ground, Tukes Valley, Pleasant Valley & Scotton Landing',
    neighborhoodDesc: 'Battle Ground\'s neighborhoods span from the historic small-city core to newer suburban developments and rural residential areas. Battle Ground has older homes along established streets. Tukes Valley is a rural-residential community with acreage properties and older homes. Pleasant Valley has a mix of newer subdivisions and established homes. Scotton Landing is a riverside community with homes that deal with moisture and wind from the Lewis River corridor.',
    cityDesc: 'Battle Ground has seen significant growth as families move north from the Portland metro. We serve both the older established homes and the newer subdivisions throughout the area.',
    roofingNote: 'North Clark County can see heavier rainfall than the immediate Portland area. Quality underlayment and properly sealed flashing are critical here.',
  },
  {
    id: 'ridgefield',
    name: 'Ridgefield',
    region: 'North & Clark County (WA)',
    neighborhood: 'Ridgefield, Union Ridge, South Ridgefield & Pioneer Street',
    neighborhoodDesc: 'Ridgefield is growing fast, and its neighborhoods reflect that expansion. Ridgefield has a small historic core with older homes and character. Union Ridge is a large newer development with well-built homes and a strong community feel. South Ridgefield has established mid-century housing that\'s been around long enough to need serious roofing attention. The Pioneer Street area has older residential blocks near the historic downtown core with homes that benefit from regular upkeep.',
    cityDesc: 'Ridgefield\'s rapid growth means a lot of newer construction with varying quality levels. We inspect and work on homes at all stages of age throughout Ridgefield.',
    roofingNote: 'Fast-growth areas like Ridgefield sometimes have builder-grade roofing installed to minimum standards. An upgrade pays for itself quickly in longevity and energy savings.',
  },
  {
    id: 'la-center',
    name: 'La Center',
    region: 'North & Clark County (WA)',
    neighborhood: 'La Center Town Center, Heisson, South La Center & Felida',
    neighborhoodDesc: 'La Center and its surrounding areas are rural and close-knit. The Town Center has older established homes along quiet streets. Heisson is a small rural community east of La Center with acreage properties and older farmhouses. South La Center has residential neighborhoods that are newer but still benefit from quality roofing attention. Felida, to the south, is an established residential area with mid-century and newer homes that we regularly serve.',
    cityDesc: 'La Center\'s rural character means homes here are often more exposed to weather than those in denser suburbs. We bring the same quality and care to every La Center project, no matter the size.',
    roofingNote: 'Rural properties in La Center face more wind and rain exposure without the protection of surrounding buildings. Extra attention to flashing and ventilation pays off here.',
  },

  // South Metro
  {
    id: 'milwaukie',
    name: 'Milwaukie',
    region: 'South Metro',
    neighborhood: 'Milwaukie, Ardenwald, Hector Campbell & Lewelling',
    neighborhoodDesc: 'Milwaukie\'s neighborhoods are close-in, well-established, and full of homes with real history. Milwaukie has a mix of older bungalows and mid-century homes along light rail corridors. Ardenwald borders Sellwood with charming older homes and a residential character that rewards quality craftsmanship. Hector Campbell is a quiet mid-century neighborhood with ranch-style homes at the roofing decision point. Lewelling is an established residential area with solid housing stock and mature trees that keep roofs and gutters working year-round.',
    cityDesc: 'Milwaukie is a close-in suburb with a strong identity and older housing stock. Many homes here are mid-century or earlier, and roofing is a common update as owners invest in their properties.',
    roofingNote: 'Milwaukie\'s older homes often have original or first-replacement roofs. If your home was built before 1990, a free inspection is a smart first step.',
  },
  {
    id: 'oregon-city',
    name: 'Oregon City',
    region: 'South Metro',
    neighborhood: 'Oregon City, Canemah, McLoughlin & Beavercreek',
    neighborhoodDesc: 'Oregon City\'s neighborhoods are steeped in history. Oregon City sits dramatically on the bluff with Victorian-era homes and historic character unmatched in the region. Canemah is one of Oregon\'s oldest surviving neighborhoods — small riverfront homes with incredible history and roofing challenges to match. McLoughlin is a mid-century residential area with ranch and split-level homes. Beavercreek is a rural-residential community outside of town with acreage homes that need roofing built for the Oregon weather.',
    cityDesc: 'As the end of the Oregon Trail, Oregon City has a proud history reflected in its older architecture. We work carefully on these historic properties, preserving character while meeting modern performance standards.',
    roofingNote: 'Oregon City\'s historic homes may have original wood shake, slate, or early asphalt roofing. We have experience with historic materials and can advise on period-appropriate replacements.',
  },
  {
    id: 'gladstone',
    name: 'Gladstone',
    region: 'South Metro',
    neighborhood: 'Gladstone Town Center, Rivercrest, Beveridge & Barlow',
    neighborhoodDesc: 'Gladstone is a small city with big residential character. The Town Center area has older homes along established streets between the two rivers. Rivercrest sits close to the Willamette with homes that deal with moisture and humidity year-round. Beveridge is a quiet residential neighborhood with mid-century housing stock. Barlow is an older area near the Clackamas River with established homes that benefit from regular roofing maintenance to stay ahead of moisture damage.',
    cityDesc: 'Gladstone is one of the metro\'s smaller cities, but we give every job here the same full attention. Many Gladstone homes are mid-century or older — prime candidates for roof inspection.',
    roofingNote: 'Homes near the river in Gladstone deal with extra moisture. Proper ventilation and quality underlayment are especially important in this zone.',
  },
  {
    id: 'canby',
    name: 'Canby',
    region: 'South Metro',
    neighborhood: 'Canby, Baker Prairie, Feyrer Park & Lone Elder',
    neighborhoodDesc: 'Canby\'s neighborhoods have a distinctly Willamette Valley small-town character. Canby has older homes on quiet residential streets with real community feel. Baker Prairie is a residential neighborhood with mid-century and newer homes outside the historic core. Feyrer Park sits near the Molalla River with homes that face extra moisture from the waterway. Lone Elder is a rural-residential area south of town with acreage properties and older farmhouses that need durable roofing for Oregon valley weather.',
    cityDesc: 'Canby sits in the agricultural heart of Clackamas County. We serve homeowners throughout Canby and the surrounding area, including rural properties on larger lots.',
    roofingNote: 'Canby\'s valley location means heavier fog and moisture in fall and winter. Moss-resistant shingles and annual gutter cleaning are smart investments here.',
  },
  {
    id: 'clackamas',
    name: 'Clackamas',
    region: 'South Metro',
    neighborhood: 'Clackamas Town Center, Sunnyside, Rock Creek & Pleasant Valley',
    neighborhoodDesc: 'The Clackamas unincorporated area has some of the metro\'s most established suburban neighborhoods. Clackamas Town Center is surrounded by 1980s–90s subdivisions with homes hitting the roofing replacement milestone. Sunnyside is a large, well-established residential area with homes from multiple eras. Rock Creek has newer residential development with well-built homes. Pleasant Valley borders Happy Valley with a mix of rural-residential and newer suburban properties — all with different roofing profiles.',
    cityDesc: 'The Clackamas unincorporated area covers a wide range of neighborhoods and home ages. We work throughout the area and can have someone out for a free estimate quickly.',
    roofingNote: 'The Clackamas area saw major development in the 1980s–2000s. Homes from that era are commonly hitting their first major roofing decision point.',
  },
  {
    id: 'happy-valley',
    name: 'Happy Valley',
    region: 'South Metro',
    neighborhood: 'Sunnyside, Clatsop Butte, Rock Creek & Damascus',
    neighborhoodDesc: 'Happy Valley\'s neighborhoods sit on the hillsides and ridges east of Portland with some of the area\'s newest and best-maintained housing. Sunnyside is the city\'s most established residential area with a mix of home ages. Clatsop Butte is a newer hillside development with custom homes and expansive views — and the complex rooflines that come with them. Rock Creek has solid newer construction throughout. Damascus to the east is a large rural-residential area with acreage homes that need roofing built for Oregon\'s wet seasons.',
    cityDesc: 'Happy Valley is one of Oregon\'s fastest-growing cities, with newer housing stock and high homeowner standards. We serve the entire Happy Valley area and consistently deliver the quality these homes deserve.',
    roofingNote: 'Happy Valley\'s hillside terrain means complex rooflines and multiple drainage paths. We inspect every valley and transition point to ensure long-term performance.',
  },
]

export function getCityById(id) {
  return CITIES.find(c => c.id === id)
}

export function getCityByName(name) {
  return CITIES.find(c => c.name === name)
}
